filebeat:
  inputs:
    type: log
    paths:
      - /dev/stderr
      - /dev/stdout 
      - /usr/share/Filebeat/test.log
  output.logstash:
    enabled: true
    hosts: ["verx_evaluation_logstash:5044"]
  
  output.console:
    enabled: true
    pretty: true
    codec.json:
      pretty: true