receivers:
 otlp:
   protocols:
     http:
       endpoint: 0.0.0.0:4318
     grpc:
       endpoint: 0.0.0.0:4317
processors:
 batch:
   # send_batch_size: 1024
   timeout: 5s
exporters:
 otlp/jaeger:
   endpoint: verx_evaluation_jaeger:4317
   tls:
    insecure: true
service:
 pipelines:
   traces:
     receivers: [otlp]
     processors: [batch]
     exporters: [otlp/jaeger]